import Head from 'next/head';
import React, { useContext } from 'react';
import { NavBar } from '../components/nav-bar';
import ApplicationContext from '../context/AppContext';
import styles from '../styles/Home.module.css';

const About = () => {
  const user = useContext(ApplicationContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar />

      <main className={styles.main}>
        <h1 className={styles.title}>About</h1>

        <p className={styles.description}>User token: {user.token}</p>
      </main>
    </div>
  );
};

export default About;
